---
title: "experimenting"
author: "Olivia Aguiar"
date: "2026-06-23"
output: html_document
---

#chunk for setting up parameter arrays and key for state variable arrays
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dde)
library(tidyverse)
#declare an array with 24 zeroes
X <- array(0, dim = c(24))
#declare an array with 52 birth rates, hibernation rate, emergence rate

b1 <- array(0, dim = c(52)) #yearling birth rate per week
b2 <- array(0, dim = c(52)) #adult birth rate per week
h <- array(0, dim = c(52)) #weekly rate of entering hibernation
#h[43] = 0.3 #this means that 30% of active bats in week 43 will enter hibernation by week 44
#h[44] = 0.3 
#h[45] = 0.3
#h[46] = 1 #fraction is 1 in the final week so all of the remaining active bats enter hibernation
e <- array(0, dim = c(52)) #weekly rate of exiting hibernation

#changed beta_h to be a constant number, because infection will start happening when individuals enter hibernation 
beta_h <- array(0.5, dim = c(52)) #weekly rate of WNS transmission

v <- array(0, dim = c(52)) #weekly rate of death from infection
r <- array(0, dim = c(52)) #weekly rate of recovery from infection
#I am keeping the natural death rate the same for now
mu_0a <- array(1/(52*30), dim = c(52))
mu_0h <- array(1/(52*30), dim = c(52))
mu_1a <- array(1/(52*30), dim = c(52))
mu_1h <- array(1/(52*30), dim = c(52))
mu_2a <- array(1/(52*30), dim = c(52))
mu_2h <- array(1/(52*30), dim = c(52))

#creating values for hibernation rate array
h[12] = 1/7
h[13] = 1/7
h[14] = 1/7
h[15] = 1/7
h[16] = 1/7
h[17] = 1/7
h[18] = 1

#creating values for emergence rate array
e[40] = 0.25
e[41] = 0.25
e[42] = 0.25
e[43] = 1


#adding values for virulence
v[27] = 0.0885 #this weekly death probability gives a 30% survival after 13 weeks
v[28] = 0.0885
v[29] = 0.0885
v[30] = 0.0885
v[31] = 0.0885
v[32] = 0.0885
v[33] = 0.0885
v[34] = 0.0885
v[35] = 0.0885
v[36] = 0.0885
v[37] = 0.0885
v[38] = 0.0885
v[39] = 0.0885

#adding values for recovery rate
r[40] = 0.25
r[41] = 0.25
r[42] = 0.25
r[43] = 1

#adding values for birth rates
#I am keeping birth rate the same for now
b1[44] = 0.094
b1[45] = 0.094
b1[46] = 0.094
b1[47] = 0.094
b1[48] = 0.094
b1[49] = 0.094
b1[50] = 0.094
b1[51] = 0.094
b1[52] = 0.094

b2[44] = 0.094
b2[45] = 0.094
b2[46] = 0.094
b2[47] = 0.094
b2[48] = 0.094
b2[49] = 0.094
b2[50] = 0.094
b2[51] = 0.094
b2[52] = 0.094



#populate array with random numbers between 1 and 100
X <- sample(1:100, 24, replace = TRUE)
#indexed starting at 1 in R not starting at 0
#[1] is S(0,m,a)
#[2] is S(0,m,h)
#[3] is S(1,m,a)
#[4] is S(1,m,h)
#[5] is S(2,m,a)
#[6] is S(2,m,h)
#[7] is I(0,m,h)
#[8] is I(0,m,a)
#[9] is I(1,m,h)
#[10] is I(1,m,a)
#[11] is I(2,m,h)
#[12] is I(2,m,a)
#[13] is S(0,f,a)
#[14] is S(0,f,h)
#[15] is S(1,f,a)
#[16] is S(1,f,h)
#[17] is S(2,f,a)
#[18] is S(2,f,h)
#[19] is I(0,f,h)
#[20] is I(0,f,a)
#[21] is I(1,f,h)
#[22] is I(1,f,a)
#[23] is I(2,f,h)
#[24] is I(2,f,a)

parameters <- c(b1, b2, mu_0a, mu_0h, mu_1a, mu_1h, mu_2a, mu_2h, beta_h, v, r, h, e, alpha = 1)
```



#chunk for the function itself
```{r}
#create a function called iterate1weekforward, that progresses state variables from a dynamical system forward one week, given a set of parameters
iterate1weekforward <- function(parameters, arrState, t) {
  #unpack parameters
  b1 <- parameters[1]
  b2 <- parameters[2]
  mu_0a <- parameters[3]
  mu_0h <- parameters[4]
  mu_1a <- parameters[5]
  mu_1h <- parameters[6]
  mu_2a <- parameters[7]
  mu_2h <- parameters[8]
  beta_h <- parameters[9]
  #search and replace beta to beta_h
  v <- parameters[10]
  r <- parameters[11]
  h <- parameters[12]
  e <- parameters[13]
  alpha <- parameters[14]

  w = t%%52+1 #have to add one bc R indexes starting at 1, not 0
  
  #unpack state variables
  S_0ma <- X[1]
  S_0mh <- X[2]
  S_1ma <- X[3]
  S_1mh <- X[4]
  S_2ma <- X[5]
  S_2mh <- X[6]
  I_0mh <- X[7]
  I_0ma <- X[8]
  I_1mh <- X[9]
  I_1ma <- X[10]
  I_2mh <- X[11]
  I_2ma <- X[12]
  S_0fa <- X[13]
  S_0fh <- X[14]
  S_1fa <- X[15]
  S_1fh <- X[16]
  S_2fa <- X[17]
  S_2fh <- X[18]
  I_0fh <- X[19]
  I_0fa <- X[20]
  I_1fh <- X[21]
  I_1fa <- X[22]
  I_2fh <- X[23]
  I_2fa <- X[24]
  #add here- I_total variable which is the sum of all I classes
  I_totalh <- I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh
  I_totala <- I_0ma + I_0fa + I_1ma + I_1fa + I_2ma + I_2fa
  
  
  X2 <- array(0, dim = c(24))
  X2[1] <- ((b1[w]/2) * (S_1fa + alpha*I_1fa)) + ((b2[w]/2) * (S_2fa + alpha*I_2fa)) + ((1-h[w])*(1-mu_0a)*S_0ma)
  X2[2] <- (1-mu_0h)*S_0mh +(h[w]*(1-mu_0a)*S_0ma) - beta_h * S_0mh * (I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[3] <- e[w]*(1-mu_0h)*S_1mh + (1-v)*(1-mu_0a)*r*I_0ma + (1-h[w])*(1-mu_1a)*S_1ma
  X2[4] <- (1-mu_1h)*S_1mh + h[w]*(1-mu_1a)*S_1ma - beta_h * S_1mh * (I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[5] <- e[w]*(1-mu_1h)*S_1mh + (1-v)*r*I_1ma + (1-h[w])*(1-mu_2a)*S_2ma
  X2[6] <- (1-mu_2h)*S_2mh + h[w]*(1-mu_2a)*S_2ma - beta_h * S_2mh * (I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[7] <- (1-v)*(1-mu_0h)*I_0mh + beta_h*S_0mh*(I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[8] <- (1-v)*(1-mu_0a)*I_0ma + (1-v)*(1-mu_0h)*e[w]*I_0mh
  X2[9] <- (1-v)*(1-mu_1h)*I_1mh + beta_h*S_1mh*(I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[10] <- (1-v)*(1-mu_1a)*I_1ma + (1-v)*(1-mu_1h)*e[w]*I_1mh
  X2[11] <- (1-v)*(1-mu_2h)*I_2mh + beta_h*S_2mh*(I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[12] <- (1-v)*(1-mu_2a)*I_2ma + (1-v)*(1-mu_2h)*e[w]*I_2mh
  X2[13] <- ((b1[w]/2) * (S_1fa + alpha*I_1fa)) + ((b2[w]/2) * (S_2fa + alpha*I_2fa)) + ((1-h[w])*(1-mu_0a)*S_0fa)
  X2[14] <- (1-mu_0h)*S_0fh +(h[w]*(1-mu_0a)*S_0fa) - beta_h * S_0fh * (I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[15] <- e[w]*(1-mu_0h)*S_1fh + (1-v)*(1-mu_0a)*r*I_0fa + (1-h[w])*(1-mu_1a)*S_1fa
  X2[16] <- (1-mu_1h)*S_1fh + h[w]*(1-mu_1a)*S_1fa - beta_h * S_1fh * (I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[17] <- e[w]*(1-mu_1h)*S_1fh + (1-v)*r*I_1fa + (1-h[w])*(1-mu_2a)*S_2fa
  X2[18] <- (1-mu_2h)*S_2fh + h[w]*(1-mu_2a)*S_2fa - beta_h * S_2fh * (I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[19] <- (1-v)*(1-mu_0h)*I_0fh + beta_h*S_0fh*(I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[20] <- (1-v)*(1-mu_0a)*I_0fa + (1-v)*(1-mu_0h)*e[w]*I_0fh
  X2[21] <- (1-v)*(1-mu_1h)*I_1fh + beta_h*S_1fh*(I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[22] <- (1-v)*(1-mu_1a)*I_1fa + (1-v)*(1-mu_1h)*e[w]*I_1fh
  X2[23] <- (1-v)*(1-mu_2h)*I_2fh + beta_h*S_2fh*(I_0mh + I_0fh + I_1mh + I_1fh + I_2mh + I_2fh)
  X2[24] <- (1-v)*(1-mu_2a)*I_2fa + (1-v)*(1-mu_2h)*e[w]*I_2fh 

return (X2)
}


```



#running the function
```{r}
X_initial <- array(0, dim = c(24))
X_initial[5] <- 100 #initializing S_2ma to 100
X_initial[17] <- 100 #initializing S_2fh to 100
X_initial[7] <- 0 #initializing I_0mh to 100

# Matrix to save all 24 state variables through time
X_history <- matrix(NA,
                    nrow = length(times),
                    ncol = 24)
# Store the initial condition
X_history[1, ] <- X_initial



#X_next <- iterate1weekforward(parameters, X_initial, 1)
#times <- seq(0, 100, by = 1)

#for (t in times) {
#  X_next <- iterate1weekforward(parameters, X_initial, t)
#  print(X_next)
  
#  X_initial = X_next
#}



times <- seq(0, 100, by = 1)
for(i in 2:length(times)) {

  X_next <- iterate1weekforward(parameters, X_initial, times[i])

  # Save this week's state
  X_history[i, ] <- X_next

  # Update the state for the next iteration
  X_initial <- X_next
}

total_pop <- rowSums(X_history)

plot(times,
     total_pop,
     type = "l",
     lwd = 2,
     xlab = "Week",
     ylab = "Total population",
     main = "Total population through time")
```

